# Reference https://github.com/python-poetry/poetry/blob/master/.pre-commit-config.yaml
# files: ^python3/
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.6
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        files: ^python3/

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        files: ^python3/

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$
        files: ^python3/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: debug-statements
